### ISSUE TITLE
EZTV RSS feed blank

### ISSUE THREAD

**Issue by purple-emily** [Gabisonfire/knightcrawler#70]
```
╰─❯ curl https://eztv1.xyz/ezrss.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:torrent="http://xmlns.ezrss.it/0.1/">
<channel>
    <title>TV Torrents RSS feed - EZTV</title>
    <link>https://eztvx.to/</link>
    <description>TV Torrents RSS feed - EZTV</description>
    <lastBuildDate>Mon, 05 Feb 2024 11:55:01 +0100</lastBuildDate>
    </channel>
</rss>
```

No data is being returned on the EZTV RSS feed. This needs keeping an eye on. Possibly need to return to a manual scrape?

**Comment by purple-emily** [comment]
This also returns blank:
```
╰─❯ curl https://eztvx.to/ezrss.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:torrent="http://xmlns.ezrss.it/0.1/">
<channel>
    <title>TV Torrents RSS feed - EZTV</title>
    <link>https://eztvx.to/</link>
    <description>TV Torrents RSS feed - EZTV</description>
    <lastBuildDate>Mon, 05 Feb 2024 11:52:01 +0100</lastBuildDate>
    </channel>
</rss>
```

**Comment by purple-emily** [comment]
This could be helpful: https://www.reddit.com/r/eztv/comments/186crt7/no_magnet_links_on_eztv/

> You can use their API. It is faster and cleaner.
> 
> https://eztv.li/api/get-torrents?limit=10&page=1
> 
> I think they want to avoid the bandwidth charge with scripts.
> 
> If you aren't scripting then you can turn on links by changing the "Layout" switch to "Default + links".

They have an API

**Comment by iPromKnight** [comment]
Seems like that mirror has gone down tbh

The main site url just shows a cloudflare error now

**Comment by purple-emily** [comment]
> Seems like that mirror has gone down tbh
> 
> The main site url just shows a cloudflare error now

Needs keeping an eye on. Their whole site has definitely gone down now. Are there any alternative crawlers we could add to grab some tv shows?

**Comment by iPromKnight** [comment]
Worth implementing once consumer rewrite is done.
Currently working through adding tests from everything
Cheers 😃
