### ISSUE TITLE
rpi 4 support

### ISSUE THREAD

**Issue by tduong-cloud** [Gabisonfire/knightcrawler#79]
Hey,

Thanks for this project. It looks really promising.

Have you planned for amr64/v8 support ?

Thanks :).

**Comment by purple-emily** [comment]
Yes, it's happening right now. You should be able to build from source.

**Comment by tduong-cloud** [comment]
Great, I will wait for the image to be downloadable on the docker hub.

Thanks!

Le mar. 6 févr. 2024, 16:24, purple_emily ***@***.***> a
écrit :

**Comment by purple-emily** [comment]
Should be fixed in #83
