### ISSUE TITLE
Fix processing of non-exact `movie` and `tv` ingested torrents

### ISSUE THREAD

**Issue by FunkeCoder23** [Gabisonfire/knightcrawler#80]
Consumers only process where the `cat` is exactly `movies` or `tv`, so external db's need to be coerced into this format

See #78

**Comment by NebKi** [comment]
I think I have a fix for this, but I'm having trouble understanding the workflow and purpose of the ingested_torrents and torrents table in the database. 

In the torrents table I see no ``tv`` category, only ``series`` and no ``movies`` but ``movie``. In the ingested_torrents there is no ``movie`` or ``series``. Which table is actually being used for the availability/real-time search check? Is there any renaming going on for the non-imported entries?

Should the categories be aligned? So only ``tv`` and ``movie`` or ``series`` and ``movie`` for both tables?

**Comment by FunkeCoder23** [comment]
Sorry, I had made a fix last night but forgot to actually make the PR. Linked the issue now

**Comment by FunkeCoder23** [comment]
> And I'm wondering, these non movies and tv entries which are not processed do show up as processed (t) in my ingested_torrents table. Does it just label it as processed, even though it didn't? If we put those to f will they be requeued for processing?

Yeah, processed will just stop the consumers from picking it up again, doesn't necessarily mean anything was found, so setting them false should allow the consumers to reprocess
