### ISSUE TITLE
Add support for securing my self hosted instance when exposed externally with Nginx Proxy Manager http basic auth with SSL certificate.

### ISSUE THREAD

**Issue by ben-2357** [Gabisonfire/knightcrawler#85]
**Is your feature request related to a problem? Please describe.**
I cannot install KnightCrawler as an addon in Stremio with http basic auth enabled (also with SSL certificate). I have tried passing the credentials in the URL like this; `https://user:password@knightcrawler.mydomain.com` but it doesn't work. Is there any other solution than using a VPN to connect to my instance?

**Describe the solution you'd like**
A way to keep other people out of my KnightCrawler instance.

**Describe alternatives you've considered**
Using a VPN. I don't want to do this, because it really defeats the purpose of Real Debrid.

**Additional context**
Stremio responds with something along the lines of; `Error adding addon to catalog`.

**Comment by purple-emily** [comment]
I can’t confirm if basic with works with Stremio but if you poke me on our discord I can help check your setup @ben-2357

**Comment by purple-emily** [comment]
@ben-2357 you’ll likely need to make a slightly altered build to get this to run right now. I am dealing with a family issue but I will add the support to make this work for you when I’m free

**Comment by purple-emily** [comment]
@ben-2357 i can likely instruct you in how to get this working if you want it doing now, again discord would be a lot easier

**Comment by trulow** [comment]
@ben-2357 What does your config look like?

I've been using knightcrawler with nginxproxymanager since the start and it's been working fine on my end.

**Comment by ben-2357** [comment]
Does that still allow external access though?

**Comment by trulow** [comment]
@ben-2357 Yes it does, however only to networks you define with the allow variable. If trying to access on a network that is not defined, it'll deny access.

**Comment by Gabisonfire** [comment]
Does the basic auth works to reach the addons when using your browser?

**Comment by ben-2357** [comment]
Yes, basic auth works great, and I can access everything in the browser fine. I think Stremio itself rejects the basic auth passed into the URL and also fails to 'plug' it back into the URL when needing to connect to the addon webpage.

**Comment by Gabisonfire** [comment]
Yeah that's more of a Stremio issue than a Knightcrawler issue. I'll wait to see if @purple-emily can get something working otherwise we should move this issue to their repos.

**Comment by purple-emily** [comment]
I also believe it's a Stremio issue. I suggest opening an issue there
