### ISSUE TITLE
GitHub action is not tagging the images as latest

### ISSUE THREAD

**Issue by purple-emily** [Gabisonfire/knightcrawler#87]
![image](https://github.com/Gabisonfire/knightcrawler/assets/93710772/5d57c225-c749-4dc0-974e-2c56bc53cdef)

I am having to manually tag the images as main at the moment. Can anyone see why the `latest` tag isn't being done?

**Comment by sleeyax** [comment]
According to the [docs](https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag), the `latest` tag is only automatically added for type `ref`, `semver` and `match` in https://github.com/Gabisonfire/torrentio-scraper-sh/blob/2cae5296a221bd7c489632fcfa2721aabc9bec9c/.github/workflows/build_images.yaml#L62. We don't use any of those. Reading further:

> You can also use the `{{is_default_branch}}` global expression to conditionally tag with latest for the default branch

So if we add that it should work. I'll create a PR.

**Comment by purple-emily** [comment]
Closed by #90 hopefully
